const cartCatalog = window.CATALOG || {};
const cartKey = 'apple-concept-cart';
const readCart = () => JSON.parse(localStorage.getItem(cartKey) || '[]');
const saveCart = cart => { localStorage.setItem(cartKey, JSON.stringify(cart)); updateCartBadge(); };
const money = value => `$${Number(value).toLocaleString()}`;
function updateCartBadge(){ const count = readCart().reduce((total,item)=>total+item.quantity,0); document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count); }
function addToCart(id){ const product=cartCatalog[id]; if(!product)return; const cart=readCart(); const existing=cart.find(item=>item.id===id); if(existing) existing.quantity+=1; else cart.push({id,quantity:1}); saveCart(cart); showCartToast(`${product.name} added to cart.`); }
function changeQuantity(id, delta){ const cart=readCart(); const item=cart.find(entry=>entry.id===id); if(!item)return; item.quantity+=delta; saveCart(cart.filter(entry=>entry.quantity>0)); renderCartPage(); }
function removeItem(id){ saveCart(readCart().filter(item=>item.id!==id)); renderCartPage(); }
function showCartToast(message){ let toast=document.querySelector('.cart-toast'); if(!toast){toast=document.createElement('div');toast.className='cart-toast';document.body.appendChild(toast)} toast.textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2200); }
function renderCartPage(){ const root=document.querySelector('#cart-root'); if(!root)return; const items=readCart().map(item=>({...item,product:cartCatalog[item.id]})).filter(item=>item.product); if(!items.length){root.innerHTML='<div class="cart-empty"><p class="eyebrow">YOUR CART</p><h1>Nothing here<br><em>yet.</em></h1><p>Your saved products will appear here.</p><a class="button button-dark" href="index.html#products">Explore products <span>↗</span></a></div>';return} const subtotal=items.reduce((total,item)=>total+item.product.price*item.quantity,0); root.innerHTML=`<div class="cart-layout"><div><a class="back-link" href="index.html#products">← Continue shopping</a><p class="eyebrow">YOUR CART</p><h1>Make it<br><em>yours.</em></h1><div class="cart-list">${items.map(item=>`<article class="cart-line"><img src="${item.product.image}" alt="${item.product.name}"><div class="cart-line-copy"><p class="product-category">${item.product.category}</p><h3>${item.product.name}</h3><p>${item.product.tagline}</p><div class="quantity-control"><button data-cart-minus="${item.id}" aria-label="Decrease quantity">−</button><span>${item.quantity}</span><button data-cart-plus="${item.id}" aria-label="Increase quantity">+</button><button class="remove-link" data-cart-remove="${item.id}">Remove</button></div></div><strong>${money(item.product.price*item.quantity)}</strong></article>`).join('')}</div></div><aside class="cart-summary"><p class="eyebrow">SUMMARY</p><div><span>Subtotal</span><strong>${money(subtotal)}</strong></div><div><span>Shipping</span><span>Calculated at checkout</span></div><div class="summary-total"><span>Total</span><strong>${money(subtotal)}</strong></div><a class="button button-dark full" href="checkout.html">Continue to checkout <span>→</span></a><p class="cart-note">Educational concept checkout. No payment is processed.</p></aside></div>`; }
function renderCheckout(){ const root=document.querySelector('#checkout-root'); if(!root)return; const items=readCart().map(item=>({...item,product:cartCatalog[item.id]})).filter(item=>item.product); if(!items.length){root.innerHTML='<div class="cart-empty"><p class="eyebrow">CHECKOUT</p><h1>Your cart is<br><em>empty.</em></h1><a class="button button-dark" href="index.html#products">Return to products <span>↗</span></a></div>';return} const total=items.reduce((sum,item)=>sum+item.product.price*item.quantity,0); root.innerHTML=`<div class="checkout-layout"><form class="checkout-form" id="checkout-form"><a class="back-link" href="cart.html">← Back to cart</a><p class="eyebrow">CHECKOUT</p><h1>Almost<br><em>there.</em></h1><div class="checkout-fields"><label>Full name<input name="name" required placeholder="Your name"></label><label>Email<input name="email" type="email" required placeholder="you@example.com"></label><label>Shipping address<textarea name="address" required rows="3" placeholder="Your shipping address"></textarea></label></div><button class="button button-dark" type="submit">Place concept order <span>↗</span></button><p class="cart-note">This educational concept flow does not collect payment or submit a real order.</p></form><aside class="cart-summary"><p class="eyebrow">ORDER SUMMARY</p>${items.map(item=>`<div class="summary-item"><span>${item.product.name} × ${item.quantity}</span><strong>${money(item.product.price*item.quantity)}</strong></div>`).join('')}<div class="summary-total"><span>Total</span><strong>${money(total)}</strong></div></aside></div>`; document.querySelector('#checkout-form').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#checkout-form').innerHTML='<div class="success-state"><p class="eyebrow">THANK YOU</p><h2>Your concept order<br><em>is ready.</em></h2><p>This demo checkout is complete. No payment was processed.</p><a class="button button-dark" href="index.html">Return home <span>↗</span></a></div>';localStorage.removeItem(cartKey);updateCartBadge();}); }

document.addEventListener('click',event=>{const add=event.target.closest('[data-add-cart]');if(add){event.preventDefault();addToCart(add.dataset.addCart)}const plus=event.target.closest('[data-cart-plus]');if(plus)changeQuantity(plus.dataset.cartPlus,1);const minus=event.target.closest('[data-cart-minus]');if(minus)changeQuantity(minus.dataset.cartMinus,-1);const remove=event.target.closest('[data-cart-remove]');if(remove)removeItem(remove.dataset.cartRemove);});
updateCartBadge(); renderCartPage(); renderCheckout();
